### ISSUE TITLE
Unable to open a jupyter notebook

### ISSUE THREAD

**Issue by MandaFry** [vivekhsridhar/tracktor#6]
Hi, very new to open cv/coding (only have some experience in R). I have been following the online instructions and up tp now everything seems to be going great! But when I try to run the code 'jupyter notebook' in comes up with the following (which I have no idea what it means).

Traceback (most recent call last):
  File "c:\users\789826\appdata\local\continuum\miniconda3\envs\fishes\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\789826\appdata\local\continuum\miniconda3\envs\fishes\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\789826\AppData\Local\Continuum\miniconda3\envs\fishes\Scripts\jupyter-notebook.EXE\__main__.py", line 5, in <module>
  File "c:\users\789826\appdata\local\continuum\miniconda3\envs\fishes\lib\site-packages\notebook\__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "c:\users\789826\appdata\local\continuum\miniconda3\envs\fishes\lib\site-packages\notebook\nbextensions.py", line 31, in <module>
    from .config_manager import BaseJSONConfigManager
  File "c:\users\789826\appdata\local\continuum\miniconda3\envs\fishes\lib\site-packages\notebook\config_manager.py", line 15, in <module>
    from traitlets.config import LoggingConfigurable
  File "c:\users\789826\appdata\local\continuum\miniconda3\envs\fishes\lib\site-packages\traitlets\__init__.py", line 1, in <module>
    from .traitlets import *
  File "c:\users\789826\appdata\local\continuum\miniconda3\envs\fishes\lib\site-packages\traitlets\traitlets.py", line 49, in <module>
    import enum
ImportError: No module named enum

Any help would be much appreciated :)

**Comment by kiview** [comment]
Hey @MandaFry,
this sounds like you are using an older version of Python (probably Python 2.x). I assume tracktor only works with Python 3.x.

**Comment by vivekhsridhar** [comment]
Dear Amanda,

Hope Kevin's suggestion solved your problem. We've tested Tracktor on all operating systems but what Kevin hints at is true. We've only ever tested it with Python 3.x
